version: "3.1"
services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8081:8081"
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8082:8082"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
