global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "checkout"
    static_configs:
      - targets:
          - "checkout:8081"
  - job_name: "loms"
    static_configs:
      - targets:
          - "loms:8082"