package domain

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/domain.LOMSCaller -o ./zzz_loms_minimock_test.go -n LOMSCallerMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LOMSCallerMock implements LOMSCaller
type LOMSCallerMock struct {
	t minimock.Tester

	funcCreateOrder          func(ctx context.Context, user int64, cartItems []CartItem) (i1 int64, err error)
	inspectFuncCreateOrder   func(ctx context.Context, user int64, cartItems []CartItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLOMSCallerMockCreateOrder

	funcStocks          func(ctx context.Context, sku uint32) (sa1 []Stock, err error)
	inspectFuncStocks   func(ctx context.Context, sku uint32)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mLOMSCallerMockStocks
}

// NewLOMSCallerMock returns a mock for LOMSCaller
func NewLOMSCallerMock(t minimock.Tester) *LOMSCallerMock {
	m := &LOMSCallerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLOMSCallerMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LOMSCallerMockCreateOrderParams{}

	m.StocksMock = mLOMSCallerMockStocks{mock: m}
	m.StocksMock.callArgs = []*LOMSCallerMockStocksParams{}

	return m
}

type mLOMSCallerMockCreateOrder struct {
	mock               *LOMSCallerMock
	defaultExpectation *LOMSCallerMockCreateOrderExpectation
	expectations       []*LOMSCallerMockCreateOrderExpectation

	callArgs []*LOMSCallerMockCreateOrderParams
	mutex    sync.RWMutex
}

// LOMSCallerMockCreateOrderExpectation specifies expectation struct of the LOMSCaller.CreateOrder
type LOMSCallerMockCreateOrderExpectation struct {
	mock    *LOMSCallerMock
	params  *LOMSCallerMockCreateOrderParams
	results *LOMSCallerMockCreateOrderResults
	Counter uint64
}

// LOMSCallerMockCreateOrderParams contains parameters of the LOMSCaller.CreateOrder
type LOMSCallerMockCreateOrderParams struct {
	ctx       context.Context
	user      int64
	cartItems []CartItem
}

// LOMSCallerMockCreateOrderResults contains results of the LOMSCaller.CreateOrder
type LOMSCallerMockCreateOrderResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for LOMSCaller.CreateOrder
func (mmCreateOrder *mLOMSCallerMockCreateOrder) Expect(ctx context.Context, user int64, cartItems []CartItem) *mLOMSCallerMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSCallerMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSCallerMockCreateOrderExpectation{}
	}

	mmCreateOrder.defaultExpectation.params = &LOMSCallerMockCreateOrderParams{ctx, user, cartItems}
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the LOMSCaller.CreateOrder
func (mmCreateOrder *mLOMSCallerMockCreateOrder) Inspect(f func(ctx context.Context, user int64, cartItems []CartItem)) *mLOMSCallerMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LOMSCallerMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by LOMSCaller.CreateOrder
func (mmCreateOrder *mLOMSCallerMockCreateOrder) Return(i1 int64, err error) *LOMSCallerMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSCallerMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSCallerMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LOMSCallerMockCreateOrderResults{i1, err}
	return mmCreateOrder.mock
}

// Set uses given function f to mock the LOMSCaller.CreateOrder method
func (mmCreateOrder *mLOMSCallerMockCreateOrder) Set(f func(ctx context.Context, user int64, cartItems []CartItem) (i1 int64, err error)) *LOMSCallerMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the LOMSCaller.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the LOMSCaller.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	return mmCreateOrder.mock
}

// When sets expectation for the LOMSCaller.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLOMSCallerMockCreateOrder) When(ctx context.Context, user int64, cartItems []CartItem) *LOMSCallerMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSCallerMock.CreateOrder mock is already set by Set")
	}

	expectation := &LOMSCallerMockCreateOrderExpectation{
		mock:   mmCreateOrder.mock,
		params: &LOMSCallerMockCreateOrderParams{ctx, user, cartItems},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up LOMSCaller.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LOMSCallerMockCreateOrderExpectation) Then(i1 int64, err error) *LOMSCallerMock {
	e.results = &LOMSCallerMockCreateOrderResults{i1, err}
	return e.mock
}

// CreateOrder implements LOMSCaller
func (mmCreateOrder *LOMSCallerMock) CreateOrder(ctx context.Context, user int64, cartItems []CartItem) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, user, cartItems)
	}

	mm_params := &LOMSCallerMockCreateOrderParams{ctx, user, cartItems}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_got := LOMSCallerMockCreateOrderParams{ctx, user, cartItems}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LOMSCallerMock.CreateOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LOMSCallerMock.CreateOrder")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, user, cartItems)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LOMSCallerMock.CreateOrder. %v %v %v", ctx, user, cartItems)
	return
}

// CreateOrderAfterCounter returns a count of finished LOMSCallerMock.CreateOrder invocations
func (mmCreateOrder *LOMSCallerMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LOMSCallerMock.CreateOrder invocations
func (mmCreateOrder *LOMSCallerMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LOMSCallerMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLOMSCallerMockCreateOrder) Calls() []*LOMSCallerMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LOMSCallerMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LOMSCallerMock) MinimockCreateOrderDone() bool {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LOMSCallerMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSCallerMock.CreateOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSCallerMock.CreateOrder")
		} else {
			m.t.Errorf("Expected call to LOMSCallerMock.CreateOrder with params: %#v", *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		m.t.Error("Expected call to LOMSCallerMock.CreateOrder")
	}
}

type mLOMSCallerMockStocks struct {
	mock               *LOMSCallerMock
	defaultExpectation *LOMSCallerMockStocksExpectation
	expectations       []*LOMSCallerMockStocksExpectation

	callArgs []*LOMSCallerMockStocksParams
	mutex    sync.RWMutex
}

// LOMSCallerMockStocksExpectation specifies expectation struct of the LOMSCaller.Stocks
type LOMSCallerMockStocksExpectation struct {
	mock    *LOMSCallerMock
	params  *LOMSCallerMockStocksParams
	results *LOMSCallerMockStocksResults
	Counter uint64
}

// LOMSCallerMockStocksParams contains parameters of the LOMSCaller.Stocks
type LOMSCallerMockStocksParams struct {
	ctx context.Context
	sku uint32
}

// LOMSCallerMockStocksResults contains results of the LOMSCaller.Stocks
type LOMSCallerMockStocksResults struct {
	sa1 []Stock
	err error
}

// Expect sets up expected params for LOMSCaller.Stocks
func (mmStocks *mLOMSCallerMockStocks) Expect(ctx context.Context, sku uint32) *mLOMSCallerMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSCallerMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSCallerMockStocksExpectation{}
	}

	mmStocks.defaultExpectation.params = &LOMSCallerMockStocksParams{ctx, sku}
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the LOMSCaller.Stocks
func (mmStocks *mLOMSCallerMockStocks) Inspect(f func(ctx context.Context, sku uint32)) *mLOMSCallerMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for LOMSCallerMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by LOMSCaller.Stocks
func (mmStocks *mLOMSCallerMockStocks) Return(sa1 []Stock, err error) *LOMSCallerMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSCallerMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSCallerMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &LOMSCallerMockStocksResults{sa1, err}
	return mmStocks.mock
}

// Set uses given function f to mock the LOMSCaller.Stocks method
func (mmStocks *mLOMSCallerMockStocks) Set(f func(ctx context.Context, sku uint32) (sa1 []Stock, err error)) *LOMSCallerMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the LOMSCaller.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the LOMSCaller.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	return mmStocks.mock
}

// When sets expectation for the LOMSCaller.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mLOMSCallerMockStocks) When(ctx context.Context, sku uint32) *LOMSCallerMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSCallerMock.Stocks mock is already set by Set")
	}

	expectation := &LOMSCallerMockStocksExpectation{
		mock:   mmStocks.mock,
		params: &LOMSCallerMockStocksParams{ctx, sku},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up LOMSCaller.Stocks return parameters for the expectation previously defined by the When method
func (e *LOMSCallerMockStocksExpectation) Then(sa1 []Stock, err error) *LOMSCallerMock {
	e.results = &LOMSCallerMockStocksResults{sa1, err}
	return e.mock
}

// Stocks implements LOMSCaller
func (mmStocks *LOMSCallerMock) Stocks(ctx context.Context, sku uint32) (sa1 []Stock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ctx, sku)
	}

	mm_params := &LOMSCallerMockStocksParams{ctx, sku}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_got := LOMSCallerMockStocksParams{ctx, sku}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("LOMSCallerMock.Stocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the LOMSCallerMock.Stocks")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ctx, sku)
	}
	mmStocks.t.Fatalf("Unexpected call to LOMSCallerMock.Stocks. %v %v", ctx, sku)
	return
}

// StocksAfterCounter returns a count of finished LOMSCallerMock.Stocks invocations
func (mmStocks *LOMSCallerMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of LOMSCallerMock.Stocks invocations
func (mmStocks *LOMSCallerMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to LOMSCallerMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mLOMSCallerMockStocks) Calls() []*LOMSCallerMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*LOMSCallerMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *LOMSCallerMock) MinimockStocksDone() bool {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockStocksInspect logs each unmet expectation
func (m *LOMSCallerMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSCallerMock.Stocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSCallerMock.Stocks")
		} else {
			m.t.Errorf("Expected call to LOMSCallerMock.Stocks with params: %#v", *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		m.t.Error("Expected call to LOMSCallerMock.Stocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LOMSCallerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateOrderInspect()

		m.MinimockStocksInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LOMSCallerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LOMSCallerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockStocksDone()
}
